### ISSUE TITLE
Reddit on mobile now blocks scrolling

### ISSUE THREAD

**Issue by stevemckenzie** [MrBukLau/filter-lists#4]
Your filters still work to hide the popovers but now you can’t scroll unless you disable content blockers and dismiss the use the app popover. 

I didn’t actually check yet but I assume they just disable overflow on the body when the popover is suppose to be visible.

**Comment by MrBukLau** [comment]
Which content blocker and device are you using? I am using AdGuard Pro on iOS, and I am able to scroll on Reddit's mobile website. However, I will have to refresh the page sometimes for scrolling to work on Reddit, but this situation is caused by the content blocker not running fast enough.

**Comment by stevemckenzie** [comment]
AdGuard but not pro and iOS as well. 

It might be that they are showing me a different popover. They seem to experiment with different versions. This one is timed base so after so long it comes back.

**Comment by MrBukLau** [comment]
I have added a new filter for Reddit to deal with the timed-based popover, but I am not sure if it works or not because I have yet to encounter it. Please update the filter lists in AdGuard and see if this new filter works or not.

**Comment by stevemckenzie** [comment]
I was just looking into this again too.. They add a `scroll-disabled` class to the body and was just trying to figure out how to use a scriptlet to remove the class name.

**Comment by stevemckenzie** [comment]
Your new rule is not working for this but seems like that rule in general should cover it. I assume its not because this is probably being added after via JS when the popover shows up.

I'm new to writing rules for adblockers but it seems like we want a scriptlet with `remove-class` with the applying option set to `stay`

**Comment by MrBukLau** [comment]
The filter would be: `reddit.com##+js(rc, scroll-disabled, body, stay)`. I have added this filter to the filter list, so all you have to do is update the filter list in AdGuard and see if this filter works or not.

**Comment by stevemckenzie** [comment]
Hmm I still seem to have this issue but that new rule seems like it should fix it.

**Comment by MrBukLau** [comment]
Did you make sure to enable Advanced Protection in AdGuard? This feature is needed for the scrolling filters to work on Reddit, but it is a premium feature only for AdGuard subscribers. If it is enabled, try turning it off and on again in the settings.

**Comment by stevemckenzie** [comment]
I didn't have the premium version. I upgraded and you are correct, all works now!

Thanks!
