### ISSUE TITLE
Amazon URL cleaner scriplet

### ISSUE THREAD

**Issue by zkisaboss** [MrBukLau/filter-lists#7]
Is it possible to update the gist to support replace the [old](https://greasyfork.org/en/scripts/376630-amazon-short-url/code) cleaner a [working](https://greasyfork.org/en/scripts/27460-amazon-url-cleaner/code) one.

**Comment by MrBukLau** [comment]
Thank you for posting that working userscript. I have removed the old one and replaced it with that one.
